//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChequeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int Id_Checks { get; set; }
        public int Id_Products { get; set; }
        public int Count { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Id_Branch { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual Product Product { get; set; }
    }
}
